name: Bug 反馈
description: 反馈与 Slimefun 汉化版相关的问题
labels: ["🐞 Bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 👋 欢迎来到 Slimefun 汉化版 Bug 追踪器
        如果你在定位问题时需要帮助, 欢迎加入我们的 [QQ 群](https://jq.qq.com/?_wv=1027&k=ESbsepYt) 了解别人是否有相同的问题.
        同样请先看看 [故障排查指南](https://slimefun.guizhanss.wiki/#/How-to-report-bugs) 和 [已知问题列表(官方)](https://github.com/Slimefun/Slimefun4/issues).
        <br /><strong><i>标注星号 (*) 的问题必须填写.</i></strong>
        <br />
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认
"
      options:
        - label: "
如果你可以自己 debug 并解决的话，提交 PR 吧
"
          required: true
        - label: "
我已经在 [Issue Tracker](……/) 中找过我要提出的问题
"
          required: true
        - label: "
我已经使用最新开发版测试过，问题依旧存在
"
          required: true
        - label: "
这是 Slimefun 汉化版的问题，并非我所使用的魔改版本的问题
"
          required: true
  - type: input
    attributes:
      label: Slimefun 版本
    validations:
      required: true
  - type: dropdown
    id: server-type
    attributes:
      label: 请选择你的服务端类型
      multiple: true
      options:
        - Paper
        - Spigot
        - Purpur
        - 其他 (下面注明)
  - type: textarea
    attributes:
      render: shell
      label: log
      description: "
请在下方描述你的问题及其复现方式
"
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true