name: Slimefun 正式版发布

on:
  push:
    tags:
      - '*'
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    if: contains(github.event.head_commit.message, '[build skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
          architecture: x64
      - run: mvn -B package --file pom.xml --errors
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/cache@v2
        if: github.event_name != 'pull_request'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v2
        if: github.event_name != 'pull_request'
        with:
          name: Slimefun.jar
          path: staging
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: github.event_name != 'pull_request'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Slimefun $GITHUB_REF_NAME"
          prerelease: false
          files: |
            target/Slimefun-*.jar