# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun DEV

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
          architecture: x64
      - run: mvn -B test --file pom.xml --errors
      - uses: actions/cache@v2
        if: github.event_name != 'pull_request'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Mask Output
        run: |
          echo "::add-mask::$CF_API_TOKEN"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Find build artifact filename
        run: |
          FILENAME=$(find . -maxdepth 1 -mindepth 1 -name "Slimefun-*" | cut -d'/' -f 2)
          echo "slimefun-artifact-name=$FILENAME" >> "$GITHUB_ENV"
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: "wrangler r2 object put slimefun-dev/${{ env.slimefun-artifact-name }} --file=./${{ env.slimefun-artifact-name }}"