name: Close invalid Pull Requests

on: 
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - master
    paths:
    - 'src/main/resources/languages/**.yml'
    
jobs:
  pulls:
    runs-on: ubuntu-latest
    steps:
    - uses: maxkomarychev/octions/octions/pulls/submit-review@master
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        pull_number: ${{ github.event.pull_request.number }}
        review_id: 1
        event: REQUEST_CHANGES
        body: |-
           Hey, it looks you edited a language file.
           
           We use [gitlocalize](https://gitlocalize.com/repo/3841) for handling localization, please don't submit any localization files
           via GitHub. That is sadly not possible.
           You can read more about how to translate Slimefun into your language [on our wiki page](https://github.com/TheBusyBiscuit/Slimefun4/wiki/Translating-Slimefun).
