name: Label approved pull requests

on: 
  pull_request_review

jobs:
  label:
    name: Label when approved
    runs-on: ubuntu-latest
    
    steps:
    - name: Label when approved
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ADD_LABEL: "Approved"
        REMOVE_LABEL: "Pending"
