# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - uses: actions/upload-artifact@v1
      with:
        name: Slimefun.jar
        path: staging
    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
          release-branch-name: "master"
          git-release-bot-name: "nameless-bot"
          git-release-bot-email: "namelessbot@starwish.io"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}  
  
