name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    paths:
    - 'src/**'
    - 'pom.xml'

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot: ["1.14.4", "1.15.2", "1.16.4"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml -Dspigot.version=${{ matrix.spigot }}
