# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slimefun 自动构建/发版

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - if: !startsWith(github.event.head_commit.message, '[build skip]')
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        java-package: jdk
        architecture: x64
    - if: !startsWith(github.event.head_commit.message, '[build skip]')
      run: mvn -B package --file pom.xml --errors
    - if: !startsWith(github.event.head_commit.message, '[build skip]')
      run: mkdir staging && cp target/*.jar staging
    - if: !startsWith(github.event.head_commit.message, '[build skip]')
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - if: !startsWith(github.event.head_commit.message, '[build skip]')
      uses: actions/upload-artifact@v2
      with:
        name: Slimefun.jar
        path: staging
    - name: Automatic Releases
      if: !startsWith(github.event.head_commit.message, '[build skip]')
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "exp"
        prerelease: true
        title: "Slimefun 自动构建版本"
        files: |
          target/Slimefun-v4.9-*.jar
