on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign_labels:
    runs-on: ubuntu-latest
    name: Categorize Pull Requests
      steps:
      - name: Branch Categorization
        uses: TheBusyBiscuit/branch-cat@v1.0.0
        with:
          rules: '[ {"fix/.*" : "bug-fix"} ]'
